English translation of readme.md
TRIGONIM/ggram pull request #1
Opened 2021-10-05 11:07 UTC by Fustie

Used:
my brains and english knownledge
https://www.deepl.com/

2021-10-05 14:51 UTC, Mudkip reviewed
А где перевод то?

Where is the actual translation? I only see Russian in the file you made.

2021-10-06 09:31 UTC, Fustie commented
> А где перевод то?
> 
> Where is the actual translation? I only see Russian in the file you made.

https://github.com/TRIGONIM/ggram/pull/1/files/5352ee17c0f06a7c2dcfbbf41c2047ef7bbf0a2b

2021-10-06 18:31 UTC, Mudkip requested changes
Подправил немного. Внеси изминения пожалуйста

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +Create Telegram bots any difficulty and start it on your own **Garry’s Mod server**
Create Telegram bots **of** any difficulty and start **them** on your own **Garry’s Mod server**

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +Extra examples can be found in directory [/bots](/lua/ggram/bots)
Extra examples can be found in the [/bots](/lua/ggram/bots) directory

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +3. Create a file `/addons/ggram_bots/lua/ggram/bots/anyname/_init.lua`.
Create **the** file `/addons/ggram_bots/lua/ggram/bots/anyname/_init.lua`

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +4. Fill it with bot example from [/bots/example](notion://www.notion.so/lua/ggram/bots/example), replacing token
Copy the code of the example bot from [/bots/example](notion://www.notion.so/lua/ggram/bots/example) into the file you just created. Do not forget to replace the token.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +## 💡 Made on GGRAM + screenshots
Made **with** GGRAM + screenshots

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +Here [(*click*)](https://forum.gm-donate.ru/t/idei-telegram-botov-dlya-vashego-servera/197) (not for English) was uploaded links on working bots, also many ideas, which you can implement with this fr
Ready-made bots, ideas that you could implement using this framework for your Garry's Mod server, and many more interesting things are posted [here (click)](https://forum.gm-donate.ru/t/idei-telegram-botov-dlya-vashego-servera/197). The possibilities are almost endless.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- Works directly with Garry’s Mod servers
Works directly **on your** Garry’s Mod servers

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- DOESN'T require any 3rd-party .dll or WEB interfaces
Does not require any additional third party .dll modules or web proxies.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- [Opportunity](/lua/ggram/includes/surprise) send animations, documents and images
[The possibility](/lua/ggram/includes/surprise) to send animations, documents, pictures.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- Created with years of experience in creating bots
Developed based on years of experience in creating bots.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- Friendly with the functional programming paradigm
Functional programming friendly.

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- 🤔 What is and how to use [update, context, middleware, reply](/info/understanding_things.md) (basic entities)
What [update, context, middleware, reply](/info/understanding_things.md) are and how to use them  (the fundamentals).

2021-10-06 18:31 UTC, Mudkip commented on readme_us.md
> +- 🗂 [Where to create bot, what to put in extensions and for what need includes](/info/project_structure.md)
[Where to create a bot, what to put in the extensions folder, and why the includes folder exists](/info/project_structure.md)

2021-10-09 10:42 UTC, AMD-NICK commented
Внеси изменения, предложенные @Mudkip, исправь картинки и можно думать про мердж

2022-04-10 22:25 UTC, Mudkip commented
Bump

2022-06-05 20:04 UTC, AMD-NICK commented
Я сильно переписал readme в целом. Нужно делать новые правки :)

2022-10-21 13:48 UTC, AMD-NICK commented
Перевел все, что нужно силами deepl.com

2022-10-21 13:48 UTC, closed without merging